version: 3

overrides:
- if: "draft or 'WIP' in title"
  status: pending

- if: "'hotfix' in labels"
  status: success

notifications:
- when: pull_request.opened
  comment: |
    Hey @{{ author }}, thanks for the PR! The review will start once
    the tests and CI checks have passed.
- when: pullapprove.approved
  if: "author_association == 'CONTRIBUTOR'"
  comment: "The review is completed. Thanks @{{ author }}, we'll take it from here."

groups:
  code:
    labels:
      approved: "Code review approved"
      pending: "Code review pending"
      rejected: "Code review rejected"
    reviews:
      required: 2
      request_order: shuffle
    reviewers:
      users:
      - shejialuo
      - North-C
      - ShuaidongGG
