name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cmake
      - run: |
          sudo apt-get update
          sudo apt-get cmake
      - name: Configure
      - run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release --build ..
      - name: Build the docx
          cmake --build . --target DOXYGEN
      - name: Build the source code and make tests
          cmake --build . && ctest
